Lec3/RecordCreation/Models/EF/User.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecordCreation.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.UserRatings = new HashSet<UserRating>();
        }
    
        public int UserId { get; set; }
        public string UserEmail { get; set; }
        public string UserName { get; set; }
        public string UserPassword { get; set; }
        public bool isActive { get; set; }
        public Nullable<int> RoleId { get; set; }
    
        public virtual Role Role { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserRating> UserRatings { get; set; }
    }
}

Lec3/RecordCreation/Controllers/UserController.cs
using RecordCreation.Models.VM;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using RecordCreation.Models.Service;

namespace RecordCreation.Controllers
{
    public class UserController : Controller
    {
        // GET: User
        public ActionResult Index()
        {
            var userList = new List<VMUser>();
            using (var service = new UserService())
            {
                 userList = service.GetAllUsers();
            }
                return View(userList);
        }
        [HttpGet]
        public ActionResult Create()
        {
            GeneratePrefillData();
            //var user = new VMUser();
           // user.usersList = GetUsers();
            return View();
        }


        public PartialViewResult ListOfUsers()
        {
            var lst = GetUsers();
            return PartialView(lst);
        }

        public List<VMUser> GetUsers()
        {
            var ser = new UserService();
            return ser.GetAllUsers();
        }

        [HttpGet]
        public ActionResult Delete(int id)
        {
            using (var service = new UserService())
            {
                service.DeleteUser(id);
            }
            return RedirectToAction("Index");
        }

        private void GeneratePrefillData(int roleId = 0)
        {
            var selectionList = new List<SelectListItem>();
            var service = new RoleService();
            var roles = service.GetList();
            foreach (var item in roles)
            {
                if (roleId == 0 || roleId != item.RoleId)
                    selectionList.Add(new SelectListItem { Value = item.RoleId.ToString(), Text = item.RoleName });
                else if (item.RoleId == roleId)
                    selectionList.Add(new SelectListItem { Value = item.RoleId.ToString(), Text = item.RoleName, Selected = true });
            }   
            ViewBag.Roles = selectionList;
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(VMUser user)
        {
            if (ModelState.IsValid)
            {
                using (var service = new UserService())
                {
                    if (service.IsValidEmail(user.UserEmail) && service.IsValidUserName(user.UserName))
                    {
                        user = service.Create(user);
                        ViewBag.Message = "User Created.";
                    }
                    else
                    {
                        ModelState.AddModelError("UserEmail", "User alredy exist");
                    }
                }
            }
            else
                ViewBag.Message = "Error In the model. Please Fix";
            //user.usersList = GetUsers();
            GeneratePrefillData();
            return View(user);
        }

        [HttpGet]
        public ActionResult Update(int id)
        {
            using (var service = new UserService())
            {
                var user = service.GetUserById(id);
                GeneratePrefillData(user.RoleId);
                return View(user);
            }
            
        }

        [HttpPost]
        public ActionResult Update(VMUser user)
        {
            if (ModelState.IsValid)
            {
                using (var service = new UserService())
                {
                        user = service.Update(user);
                        ViewBag.Message = "User Updated.";
                    return RedirectToAction("Index");
                }
            }
            else
                ViewBag.Message = "Error In the model. Please Fix";

            GeneratePrefillData(user.RoleId);
            return View(user);
        }


        [HttpGet]
        public ActionResult Details(int id)
        {
            using (var service = new UserService())
            {
                var user = service.GetUserById(id);
                var vmUser = new UserRatingVM();
                vmUser.Users = user;
                vmUser.Ratings = service.GetAllRatings(id);
                return View(vmUser);
            }

        }
    }
}

Lec3/RecordCreation/Controllers/UserRatingController.cs
using RecordCreation.Models.EF;
using RecordCreation.Models.VM;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RecordCreation.Controllers
{
    public class UserRatingController : Controller
    {
        // GET: UserRating
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Create(int Id)
        {
            ViewBag.UserId = Id;
            return View();
        }

        [HttpPost]
        public ActionResult Create(RatingVM rating,string UserId)
        {
            using (var db = new Entities())
            {
                db.UserRatings.Add(new UserRating { RatingDateTime = rating.RatingDateTime, RatingNo = rating.RatingNo, UserId = int.Parse(UserId)});
                db.SaveChanges();
            }
            return RedirectToAction("Details", "User", new { id = UserId });
        }
    }
}

Lec3/RecordCreation/Views/User/Create.cshtml
@model RecordCreation.Models.VM.VMUser
@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>



@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    @Html.ValidationSummary(false,"",new { @class = "text-danger" })
 <div class="form-horizontal">
        <hr />
        <div class="form-group">
            @Html.LabelFor(model => model.UserEmail, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.UserEmail, new { @class = "form-control " } )
                @Html.ValidationMessageFor(m=>m.UserEmail,"",new { @class="text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UserName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                    @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(m => m.UserName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UserPassword, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                    @Html.PasswordFor(model => model.UserPassword, new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Verify Password", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.PasswordFor(model=>model.Password2, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.Password2, "", new { @class = "text-danger" })
            </div>
        </div>

     <div class="form-group">
         @Html.LabelFor(m=>m.RoleName, htmlAttributes: new { @class = "control-label col-md-2" })
         <div class="col-md-10">
             @Html.DropDownListFor(model => model.RoleId, ViewBag.Roles as List<SelectListItem>, new { @class = "form-control" })
             @Html.ValidationMessageFor(m => m.Password2, "", new { @class = "text-danger" })
         </div>
     </div>

        <div class="form-group">
            @Html.LabelFor(model => model.isActive, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.CheckBoxFor(model => model.isActive)
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>

      @*@Html.EditorForModel()*@
}



<h1>List Of Users</h1>
@*@Html.Partial("_ShowUser", Model.usersList); *@
@Html.Action("ListOfUsers")
<br />
@{ 
    Html.RenderAction("ListOfUsers");
}



@section MyFooterName{
   @Html.Action("ListOfUsers")
}


@section BeforeBody{
    <h1>Hi I am before body</h1>
}

Lec3/RecordCreation/Views/User/Details.cshtml
@model RecordCreation.Models.VM.UserRatingVM
@{
    ViewBag.Title = "Details";

}

@helper GetListAsLi(List<double> myRating){
    foreach (var item in myRating)
    {
    <li> @item.ToString() </li>
    }
}
<h2>Details</h2>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Users.UserName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Users.UserEmail)
        </dd>

        <dt>
            <dt>
            @Html.LabelFor(model=>model.Users.isActive)
                </dt>
        <dd>
            @{ var val = Model.Users.isActive ? "Yes" : "No";}
            @val
        </dd>
        </dt>
    </dl>
</div>

<ul>
    @GetListAsLi(Model.Ratings.Select(a=>a.RatingNo).ToList())
</ul>
@Html.GetListInLI(Model.Ratings.Select(a => a.RatingNo).ToList())

@Html.ActionLink("Create", "Create", "UserRating", new { Id = Model.Users.UserId }, new { })

@Html.Partial("_RatingList",Model.Ratings)

@section scripts{
@Scripts.Render("~/bundles/bootstrap")
@Styles.Render("~/Content/css")
    }

Lec3/RecordCreation/Views/User/Index.cshtml
@model List<RecordCreation.Models.VM.VMUser>
@{
    ViewBag.Title = "Index";
}

<h2>Listing</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            Email
        </th>
        <th>
           User Name
        </th>
        <th>
            Role Name
        </th>
        <th>
            
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.UserEmail)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.UserName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.RoleName)
            </td>
            <td>
                @Html.ActionLink("Edit", "Update", new { id = item.UserId}) |
                @Html.ActionLink("Details", "Details", new { id = item.UserId }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.UserId })
            </td>
        </tr>
    }
  
</table>

Lec3/RecordCreation/Views/User/ListOfUsers.cshtml
@model List<RecordCreation.Models.VM.VMUser>

<table>
    <thead>
    <th>
        User Name
    </th>
    <th>
        Email
    </th>
    <th>
        Role Name
    </th>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @item.UserName
                </td>
                <td>
                    @item.UserEmail
                </td>
                <td>
                    @item.RoleName
                </td>
            </tr>
        }
    </tbody>
</table>

Lec3/RecordCreation/Views/User/Update.cshtml
@model RecordCreation.Models.VM.VMUser
@{
    ViewBag.Title = "Update";
}

<h2>Update</h2>


@using (Html.BeginForm())
{
    @Html.ValidationSummary(false, "", new { @class = "text-danger" })
    <div class="form-horizontal">
        <hr />
        @Html.HiddenFor(m=>m.UserId)
        <div class="form-group">
            @Html.LabelFor(model => model.UserEmail, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.UserEmail, new { @class = "form-control " })
                @Html.ValidationMessageFor(m => m.UserEmail, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UserName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(m => m.UserName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UserPassword, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.PasswordFor(model => model.UserPassword, new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Verify Password", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.PasswordFor(model => model.Password2, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.Password2, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.RoleName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.RoleId, ViewBag.Roles as List<SelectListItem>, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.Password2, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.isActive, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.CheckBoxFor(model => model.isActive)
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Update" class="btn btn-default" />
            </div>
        </div>
    </div>

    @*@Html.EditorForModel()*@
}